### PR TITLE
Add resource to manage kibana space

### PR DESCRIPTION
**Pull request by jfroche**
require ewilde/go-kibana#31 to be merged

We have to enable xpack security in elasticsearch and kibana. We enable
xpack security using an environment variable (USE_XPACK_SECURITY) during
the tests.

### CODE REVIEW

**Comment by ewilde** [comment]
Thank you @jfroche I will review your PR tomorrow 🙏

**Comment by ewilde** [comment]
@jfroche apologies for late review once we have https://github.com/ewilde/go-kibana/pull/31 fixed and merged, can you update this vendor directory in this PR to reflect 🙏

**Comment by ewilde** [comment]
@jfroche sorry with your https://github.com/ewilde/terraform-provider-kibana/pull/28 now merged this has caused conflicts, would you mind resolving ? 👍

**Comment by jfroche** [comment]
fixed conflicts / rebased

**Pull request merged**
