### PR TITLE
Use go modules and terraform 0.12

### PR DESCRIPTION
**Pull request by jfroche**

### CODE REVIEW

**Comment by jfroche** [comment]
You might want to fork and push your change here first: ewilde/go-kibana@0f99f55 in vendor/gopkg.in/ory-am/dockertest.v3/dockertest.go

**Comment by ewilde** [comment]
@jfroche thank you for this contribution 👍 is it fair to say that this PR is more upgrade to use go modules

Seems like to fully migrate to terraform 0.12 we would also need to upgrade the test terraform to use the new syntax? https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html#configuration-syntax-changes

What do you think?

**Comment by jfroche** [comment]
@devenney I couldn't not figure how to fix the nul pointer exception we get using terraform 0.12 with the embedding that you use for the provider configuration (created here: https://github.com/ewilde/terraform-provider-kibana/commit/062f4fa68ce727ffb858356d882457632589aebd#diff-b599b4b324320f20dfd6aaa8d6bfba9b)

Here is the exception when we keep the embedding:

```
2019/09/10 22:46:25 Elastic 6.4.1 search (elasticsearch): up
2019/09/10 22:46:37 Kibana 6.4.1 (kibana): up
=== RUN   TestAccDataSourceKibanaIndex_Basic
2019/09/10 22:46:37 [DEBUG] Test: Executing step 0
2019/09/10 22:46:37 [TRACE] ModuleInstaller: installing child modules for /tmp/tf-test029800410 into /tmp/tf-test029800410/.modules
2019/09/10 22:46:37 [TRACE] modsdir: writing modules manifest to /tmp/tf-test029800410/.modules/modules.json
2019/09/10 22:46:37 [TRACE] terraform.NewContext: starting
2019/09/10 22:46:37 [TRACE] terraform.NewContext: resolving provider version selections
2019/09/10 22:46:37 [TRACE] terraform.NewContext: loading provider schemas
2019/09/10 22:46:37 [TRACE] LoadSchemas: retrieving schema for provider type "kibana"
2019/09/10 22:46:37 [TRACE] GRPCProvider: GetSchema
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfcc0a1]

goroutine 204 [running]:
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).getProviderSchemaBlock(...)
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:76
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).GetSchema(0x0, 0x16397a0, 0xc0001bdda0, 0xc000493320, 0x0, 0xc0001bdda0, 0xc0004eeba8)
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/github.com/hashicorp/terraform/helper/plugin/grpc_provider.go:55 +0x91
github.com/hashicorp/terraform/internal/tfplugin5._Provider_GetSchema_Handler(0x12f0180, 0x0, 0x16397a0, 0xc0001bdda0, 0xc000490a00, 0x0, 0x16397a0, 0xc0001bdda0, 0x0, 0x0)
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/github.com/hashicorp/terraform/internal/tfplugin5/tfplugin5.pb.go:3073 +0x23e
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000469500, 0x16486e0, 0xc000469c80, 0xc0004e5300, 0xc000329d70, 0x1fbdf40, 0x0, 0x0, 0x0)
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/google.golang.org/grpc/server.go:998 +0x470
google.golang.org/grpc.(*Server).handleStream(0xc000469500, 0x16486e0, 0xc000469c80, 0xc0004e5300, 0x0)
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/google.golang.org/grpc/server.go:1278 +0xda6
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000480820, 0xc000469500, 0x16486e0, 0xc000469c80, 0xc0004e5300)
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/google.golang.org/grpc/server.go:717 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/jfroche/projects/bric/elk/terraform-provider-kibana/vendor/google.golang.org/grpc/server.go:715 +0xa1
FAIL    github.com/ewilde/terraform-provider-kibana/kibana      33.677s
```
GetSchema is defined on `*schema.Provider` (so should be accessible in KibanaProvider) and I don't get why Provider is nil. Any clue ? I pushed the failing code here: https://github.com/jfroche/terraform-provider-kibana/tree/feature/terraform-0.12-embbeding

**Comment by devenney** [comment]
Thanks for the detail @jfroche. Looking at the code, I think it might be an issue with the error scope. I suspect the error is getting swallowed and thus the client is returned as `nil` rather than exiting with error output.

I'll take a look at this tomorrow and see if I can reproduce/fix. Could I ask where you're seeing the nil pointer? Is it in a Travis log, local testing, or in a packaged provider built for 0.12?

**Comment by devenney** [comment]
This is resolved in v0.7.0. Let me know if you experience any issues.

**Pull request closed without merging**
